---
roles:
  - name: deploy-container
    src: https://github.com/marcelofpfelix/ansible-role-deploy-container.git
    scm: git
    version: main
collections:
  - name: community.docker
  - name: geerlingguy.mac
    version: ">=2.3.0"
  - name: community.general
